apiVersion: v1
kind: Service
metadata:
  name: mall-portal-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: mall-portal
  ports:
    - name: http
      protocol: TCP
      port: 8085
      targetPort: 8085