apiVersion: v1
kind: Service
metadata:
  name: mall-search-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: mall-search
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081